# Generated by Django 3.2.11 on 2022-03-06 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_blogpage_categories'),
        ('blog', '0013_alter_formpage_body'),
    ]

    operations = [
    ]
