# Generated by Django 3.2.11 on 2022-03-06 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pelis', '0005_auto_20220208_1037'),
        ('pelis', '0005_auto_20220208_1042'),
    ]

    operations = [
    ]
